### PR TITLE
Fix interface member references

### LINKED ISSUE #108: Interface members with refkeys cause issues in InterfaceExpression
InterfaceExpression doesn't create a member scope. Perhaps a similar pattern to object expressions should be used - object expressions will check if there is an assignment symbol and if so, wrap its children in a MemberScope with an owner of that assignment symbol. This would mean, given:

```ts
interface Foo {
  outer: {
    inner: string;
  }
}
```

that the outer symbol would become a `SymbolFlags.StaticMemberContainer` and the symbol for `inner` would be a static member of the `outer` symbol.

### LINKED ISSUE #111: Type reference to interface members seems broken
```ts
 <>
        <ts.InterfaceDeclaration name="Foo">
              <ts.InterfaceMember name="prop" type="string" refkey={ref} />
        </ts.InterfaceDeclaration>
        <line />
        <ts.InterfaceDeclaration name="Bar">
          <ts.InterfaceMember name="ref" type={<Reference refkey={ref} />} />
        </ts.InterfaceDeclaration>
      </>,
```

Produce `Foo.prop` but it should be `Foo["prop"]`

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #108 
fix #111

### CODE REVIEW

File: packages/typescript/src/components/Interface.tsx [hunk 1]
```diff
@@ -87,9 +108,18 @@ export function InterfaceMember(props: InterfaceMemberProps) {
...
+      const sym = createTSSymbol({
+        name,
+        scope: memberScope.staticMembers as TSOutputScope,
+        refkey: props.refkey,
+        flags: OutputSymbolFlags.StaticMember,
+        tsFlags: TSSymbolFlags.TypeSymbol,
+      });
       return (
-        <MemberDeclaration static name={name} refkey={props.refkey}>
+        <MemberDeclaration static symbol={sym} refkey={props.refkey}>
```
Comment (bterlson) [inline packages/typescript/src/components/Interface.tsx:122]: don't need to pass refkey here now.

Comment (bterlson) [reply packages/typescript/src/components/Interface.tsx:122]: Also could probably stand to have the TypeScript equivalent of `MemberDeclaration`.

**Review by bterlson — APPROVED** [review]
Small nits but this is amazing!

File: packages/typescript/src/components/MemberDeclaration.tsx [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+   */
+  flags?: OutputSymbolFlags;
+
+  /**
+   * The symbol to use for this memberdeclaration.
+   */
+  symbol?: TSOutputSymbol;
+}
+
+export function MemberDeclaration(props: Readonly<MemberDeclarationProps>) {
```
Comment (bterlson) [inline packages/typescript/src/components/MemberDeclaration.tsx:45]: Can we get a changelog entry for this component?

**Review by bterlson — APPROVED** [review]
